apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./foodbyte-frontend
      sourceRef:
        kind: GitRepository
        name: foodbyte-charts
        namespace: flux-system
  values:
    replicaCount: 2
    imagePullSecrets:
      - name: ghcr-pull-secret
    image:
      tag: "60a7ed6b23ccdbf539cc2c4a72d406352ffb1a76"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
