apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notification-service
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./foodbyte-notification-service
      sourceRef:
        kind: GitRepository
        name: foodbyte-charts
        namespace: flux-system
  values:
    replicaCount: 2
    useSecrets: true
    externalDatabase:
      enabled: false
    imagePullSecrets:
      - name: ghcr-pull-secret
    image:
      tag: "7ed02c635a6ebeb156a675a267d48ba3aff8a0b5"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
