apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: user-service
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./foodbyte-user-service
      sourceRef:
        kind: GitRepository
        name: foodbyte-charts
        namespace: flux-system
  values:
    replicaCount: 2
    useSecrets: true
    externalDatabase:
      enabled: false
    imagePullSecrets:
      - name: ghcr-pull-secret
    image:
      tag: "3b65f1a5f6b9c0a6c9a6b3ce79ace4df945bf4da"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
